# Generated by Django 2.2.9 on 2020-03-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='board_type',
        ),
    ]
