# Generated by Django 2.2.10 on 2020-03-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contents',
            new_name='description',
        ),
    ]
